### ISSUE TITLE
"reaver" headers

### ISSUE THREAD

**Issue by dubik** [reaver-project/vapor#51]
hi,
I tried to compile vapor, but it fails because of `reaver/future_get.h` and later `reaver/optional.h`. They don't seem to be used, but there are cases when reaver stuff is used like `class unterminated_comment : public reaver::exception`. Where to get it?

**Comment by griwes** [comment]
Hi!

Nice to see someone take a look at this ;)

The reaver headers come from https://github.com/reaver-project/reaverlib; currently I'm using `master` of that project directly.
